### ISSUE TITLE
Fix punctuation of Ingredients lists

### ISSUE THREAD

**Issue by markconroy** [gareth-fivemile/demo_umami#31]
**fine yellow cornmeal for dusting** on the pizza recipe should probably read **Fine yellow cornmeal for dusting**

**Comment by JayKandari** [comment]
@markconroy : Can we add another similar issue to this. As IMO, this issue and the issue below would require a similar approach. 
![image](https://user-images.githubusercontent.com/1266231/34716722-b731148c-f556-11e7-83bc-b4199defc3d6.png)
Notice the HTML entity `&#189;`. These are not getting converted when viewing. Since Ingredients is a Plain(text) field only. HTML entities are not rendered to their special characters. Same goes with few other content as well. 

We have marked this as important for 15 Jan. Suggestions 
cc: @kjays

**Comment by thamas** [comment]
I think it should be corrected in the source.

**Comment by navneet0693** [comment]
@markconroy This content has been removed I guess, I am not able to find it now.

**Comment by markconroy** [comment]
Let's close the issue so. Thanks @navneet0693
